import { z } from 'zod';
import type { DigestStore } from '../domain/digestGeneration.js';
import type { Digest, DigestEmailItem, DigestSection } from '../domain/digest.js';
import { EMAIL_CATEGORIES } from '../domain/summary.js';
import type { Logger } from '../logging/logger.js';
import type { FirestoreLike } from './usersRepository.js';

/**
 * Firestore-backed `digests` collection (TICKET-105), one document per user per day.
 * Keyed by `${uid}_${date}` — a composite, human-legible id chosen instead of an
 * autogenerated one specifically so that re-running the generation job for the same day is
 * a create-then-update against the same document, never a duplicate (the idempotent-write
 * pattern shared with `gmailSyncStateRepository` and `summaryCacheRepository`).
 */
const DIGESTS_COLLECTION = 'digests';

/** The gRPC status code Firestore raises from `create()` on a conflicting document. */
const FIRESTORE_ALREADY_EXISTS_CODE = 6;

/** Ids are interpolated into a document path; a Google user id is a URL-safe token and a
 * date is always `YYYY-MM-DD`, so anything else at this boundary is rejected rather than
 * risking a path escape into another user's document. */
const SAFE_UID = /^[A-Za-z0-9-]+$/;
const DATE_KEY = /^\d{4}-\d{2}-\d{2}$/;

const DigestEmailItemDocument = z.object({
  messageId: z.string().min(1),
  from: z.string(),
  subject: z.string(),
  summary: z.string().min(1).nullable(),
  urgent: z.boolean(),
  receivedAt: z.string().min(1),
});

const DigestSectionDocument = z.object({
  category: z.enum(EMAIL_CATEGORIES),
  items: z.array(DigestEmailItemDocument),
});

const DigestDocument = z.object({
  date: z.string().regex(DATE_KEY),
  userId: z.string().min(1),
  sections: z.array(DigestSectionDocument),
  generatedAt: z.string().min(1),
  emailCount: z.number().int().nonnegative(),
});

export interface DigestRepositoryOptions {
  /** Receives a warning when a stored document is invalid; never document contents. */
  readonly logger?: Logger;
}

export function createFirestoreDigestStore(
  firestore: FirestoreLike,
  options: DigestRepositoryOptions = {},
): DigestStore {
  const collection = firestore.collection(DIGESTS_COLLECTION);

  function documentId(uid: string, date: string): string | null {
    if (!SAFE_UID.test(uid) || !DATE_KEY.test(date)) {
      options.logger?.warn('digest document id rejected by shape check', {
        uidLength: uid.length,
      });
      return null;
    }
    return `${uid}_${date}`;
  }

  return {
    async get(uid, date) {
      const id = documentId(uid, date);
      if (id === null) {
        return null;
      }
      const snapshot = await collection.doc(id).get();
      if (!snapshot.exists) {
        return null;
      }
      const parsed = DigestDocument.safeParse(snapshot.data());
      if (!parsed.success) {
        // A corrupt document must not wedge the read path or the generation job forever;
        // treating it as absent forces a fresh generation, which overwrites it.
        options.logger?.warn('digest document invalid; treating as absent', { uid, date });
        return null;
      }
      // The stored id must agree with the document it was fetched under — the id-derived
      // fields are the ones that matter (see summaryCacheRepository for the same defense).
      if (parsed.data.userId !== uid || parsed.data.date !== date) {
        options.logger?.warn('digest document key mismatch; treating as absent', { uid, date });
        return null;
      }
      return toDigest(parsed.data);
    },

    async save(digest) {
      const id = documentId(digest.userId, digest.date);
      if (id === null) {
        throw new Error('digest save rejected: uid or date failed the safe-id shape check');
      }
      const document = collection.doc(id);
      const data = toDocument(digest);
      try {
        await document.create(data);
      } catch (error) {
        if (!isAlreadyExists(error)) {
          throw error;
        }
        await document.update(data);
      }
    },
  };
}

function toDigest(document: z.infer<typeof DigestDocument>): Digest {
  return {
    date: document.date,
    userId: document.userId,
    generatedAt: document.generatedAt,
    emailCount: document.emailCount,
    sections: document.sections.map(
      (section): DigestSection => ({
        category: section.category,
        items: section.items.map(
          (item): DigestEmailItem => ({
            messageId: item.messageId,
            from: item.from,
            subject: item.subject,
            summary: item.summary,
            urgent: item.urgent,
            receivedAt: item.receivedAt,
          }),
        ),
      }),
    ),
  };
}

function toDocument(digest: Digest): Record<string, unknown> {
  return {
    date: digest.date,
    userId: digest.userId,
    generatedAt: digest.generatedAt,
    emailCount: digest.emailCount,
    sections: digest.sections.map((section) => ({
      category: section.category,
      items: section.items.map((item) => ({
        messageId: item.messageId,
        from: item.from,
        subject: item.subject,
        summary: item.summary,
        urgent: item.urgent,
        receivedAt: item.receivedAt,
      })),
    })),
  };
}

function isAlreadyExists(error: unknown): boolean {
  if (typeof error !== 'object' || error === null) {
    return false;
  }
  const { code } = error as { code?: unknown };
  return code === FIRESTORE_ALREADY_EXISTS_CODE;
}
